spring:
  application:
    name: myshop-service-reg
  datasource:
    druid:
      url: jdbc:mysql://sh-cdb-hlkfo8mc.sql.tencentcdb.com:63962/myshop?useUnicode=true&characterEncoding=utf8&useSSL=false
      username: myshop
      password: myshop123456
      # 初始连接数
      initialSize: 5
      # 最小连接池数量
      minIdle: 10
      # 最大连接池数量
      maxActive: 20
      test-on-borrow: true
      driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        port: 8719
        dashboard: 127.0.0.1:8080
server:
  port: 9501
mybatis:
  type-aliases-package: com.pda.myshop.commons.domain
  mapper-locations: classpath:mapper/*.xml
management:
  endpoints:
    web:
      exposure:
        include: "*"